cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'atom'
cask 'garmin-express'
cask 'google-chrome'
cask 'handbrake'
cask 'inkscape'
cask 'slack'
cask 'sourcetree'
cask 'vlc'

tap 'caskroom/versions'
cask 'firefoxdeveloperedition'
